export const DOCTYPE_LIST = {
    IMPORT_SEA_HOUSE_BILL: {
        NAME: "Import Sea House Bill",
        CHILD_DOCTYPE: {
            CONTAINER_INFO: {
                name: "container_info",
                fields: [
                    { name: "name", label: "Id" },
                    { name: "custom_container_no", label: "Container No" },
                    { name: "size", label: "Size" },
                    { name: "no_of_pkg", label: "No of Pkg" },
                    { name: "weight", label: "Weight" },
                    { name: "con_type", label: "Container Type" },
                    { name: "status", label: "Status" },
                    { name: "seal_no", label: "Seal No" },
                    { name: "imco", label: "IMCO" },
                    { name: "un", label: "UN" },
                    { name: "ctn_location", label: "Container Location" },
                    { name: "commodity_code", label: "Commodity Code" },
                    { name: "weight", label: "Weight" },
                    { name: "cbm", label: "CBM" },
                    { name: "description", label: "Description" },
                ],
            },
            INVOICE_LIST: {
                name: "invoice_list",
                fields: [
                    { name: "name", label: "Id" },
                    { name: "invoice_link", label: "Invoice No" },
                    { name: "customer", label: "Customer" },
                    { name: "date", label: "Invoice Date" },
                    { name: "item_code", label: "Item Code" },
                    { name: "qty", label: "QTY" },
                    { name: "rate", label: "Rate" },
                    { name: "total_price", label: "Amount" },
                    { name: "currency", label: "Currency" },
                    { name: "exchange_rate", label: "Exchange Rate" },
                    { name: "base_net_amount", label: "Net Amount" },
                ],
            },
            EXPENSE_LIST: {
                name: "purchase_invoice_list",
                fields: [
                    { name: "name", label: "Id" },
                    { name: "invoice_link", label: "Invoice No" },
                    { name: "date", label: "Invoice Date" },
                    { name: "supplier", label: "Supplier" },
                    { name: "item_code", label: "Item Code" },
                    { name: "qty", label: "Qty" },
                    { name: "rate", label: "Rate" },
                    { name: "amount", label: "Amount" },
                    { name: "currency", label: "Currency" },
                    { name: "exchange_rate", label: "Exchange Rate" },
                    { name: "total_price", label: "Net Amount" },
                ],
            },
        },
    },
};
